include(CMakeFindDependencyMacro)

set(LIBXML2_SHARED @BUILD_SHARED_LIBS@)
set(LIBXML2_WITH_ICONV @LIBXML2_WITH_ICONV@)
set(LIBXML2_WITH_THREADS @LIBXML2_WITH_THREADS@)
set(LIBXML2_WITH_ICU @LIBXML2_WITH_ICU@)
set(LIBXML2_WITH_LZMA @LIBXML2_WITH_LZMA@)
set(LIBXML2_WITH_ZLIB @LIBXML2_WITH_ZLIB@)

if(LIBXML2_WITH_ZLIB)
  message(STATUS "LibXml2 find dependency ZLIB:")
  set(ZLIB_DIR ${ZLIB_DIR})
  message(STATUS "ZLIB_DIR: ${ZLIB_DIR}")
  set(ZLIB_DIR ${ZLIB_DIR} CACHE PATH "Path to zlib-config.cmake file.")
  find_dependency(ZLIB CONFIG)
  message(STATUS "CONFIG ZLIB: ${ZLIB_FOUND}.")
  find_package(ZLIB CONFIG)
  message(STATUS "CONFIG ZLIB 2: ${ZLIB_FOUND}.")
  
  if (NOT ZLIB_FOUND)
    find_dependency(ZLIB REQUIRED)
  endif()
  list(APPEND LIBXML2_LIBRARIES zlib)
  list(APPEND LIBXML2_INTERFACE_LINK_LIBRARIES "zlib")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/libxml2-exports.cmake")
